# Top level build settings
[build-system]
requires = [
    "setuptools>=64.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


# See this for settings: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
[project]
name = "comp-flow"
version = "0.0.dev0"
authors = [
    {name = "David D. Marshall", email = "ddmarshall@gmail.com"},
]
description = "Python library for modeling compressible flows."
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "license.md"}
keywords = [
    "Compressible Flow",
    "Gas Dynamics",
    ""
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering"
]
dependencies = [
    "numpy>=1.20",
    "scipy>=1.8"
]

[project.urls]
#documentation = "https://ddmarshall.github.io/IBL/index.html"
repository = "https://github.com/ddmarshall/comp-flow"

[project.optional-dependencies]
examples = ["matplotlib>=3.5"]
tests = [
    "pylint>=2.15",
    "mypy>=0.991",
    "pycodestyle>=2.10",
    "coverage[toml]>=7.2",
    "tox>=4.4",
    "sphinx-rtd-theme>=0.4.3"
]


# Setuptools settings
[tool.setuptools]
packages=["compflow"]
include-package-data = true

[tools.setuptools.packages.find]
where = ["compflow"]

[tools.setuptools.package-data]
#stanford_olympics = ["*.txt"]


# Mypy settings
[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
files = [
    "compflow",
    "examples",
    "tests"
]

[[tool.mypy.overrides]]
module = [
    "scipy.*",
    "matplotlib.*"
]
ignore_missing_imports = true


# Pylint settings
[tool.pylint.basic]
good-names-rgxs = ["^[_a-z][_a-z0-9]?$"]

[tool.pylint.design]
max-args = 10
max-attributes = 20
max-locals = 20
max-public-methods = 30
min-public-methods = 1

[tool.pylint.format]
max-line-length = 79

[tool.pylint.similarities]
min-similarity-lines = 12

# Coverage.py settings
[tool.coverage.run]
branch = true
command_line = "-m unittest discover --start-directory tests"

